name: DeployArticle

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -f Dockerfile -t writing_article --no-cache .

    - name: Run the Docker image
      run: |
        docker run -i -v $(pwd):/tmp writing_article:latest

    - name: git setting
      run: |
        git config --local user.name "satoichi"
        git config --local user.email "3101taichi@gmail.com"

    - name: git add
      run: |
        git add .

    - name: git commit
      run: |
        git commit -m "post"

    - name: git pull
      run: |
        git pull

    - name: git push
      run: |
        git push
